name: Eliassen QA Tests with CI Reporter
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      working-directory: ./eliassen-qa
      run: npm ci
      
    - name: Install Playwright Browsers
      working-directory: ./eliassen-qa
      run: npx playwright install --with-deps
      
    - name: Run Eliassen QA Tests with CI Reporter
      uses: ./qa-cicd-reporter
      with:
        test-command: 'cd eliassen-qa && npm test'
        test-results-path: 'eliassen-qa/test-results/results.xml'
        report-title: '🏢 Eliassen QA Test Results - ${{ github.event.head_commit.message || github.event.pull_request.title }}'
        notification-channels: 'console'
        include-screenshots: true
        fail-on-test-failure: true
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: eliassen-qa/playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: eliassen-qa/test-results/
        retention-days: 30
